# Generated by Django 6.0 on 2025-12-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField()),
                ('description', models.CharField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('department', models.CharField()),
                ('image', models.FilePathField()),
                ('contact_number', models.CharField()),
                ('email', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('department', models.CharField()),
                ('program', models.CharField()),
                ('year', models.CharField()),
                ('section', models.CharField()),
                ('contact_number', models.CharField()),
                ('email', models.CharField()),
                ('image', models.FilePathField()),
            ],
        ),
    ]
